# Generated by Django 2.2.2 on 2019-11-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_auto_20191118_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='category',
        ),
        migrations.AddField(
            model_name='album',
            name='category',
            field=models.CharField(choices=[('soil', 'Soil'), ('water', 'Water'), ('air', 'Air'), ('light', 'Light')], default='soil', max_length=6),
        ),
    ]
